### ISSUE TITLE
iOS Shadow

### ISSUE THREAD

**Issue by darkmantle** [bradmartin/nativescript-floatingactionbutton#91]
For some reason shadow is not showing up on iOS (Angular). Not sure if it should be automatic or if I have to apply CSS shadows? 

Using version 4.1.4

```html
<FAB row="0" (tap)="fabTap()" icon="~/images/map.png" rippleColor="#f1f1f1" class="fab-button"></FAB>
```

```css
.fab-button {
    height: 70;
    width: 70;
    margin: 15;
    background-color: white; 
    horizontal-align: right; 
    vertical-align: bottom; 
}
```
